### ISSUE TITLE
Custom button for adding own task

### ISSUE THREAD

**Issue by GiovaniFuentes** [nmsu-cs/project-macintosh-mavericks-1#14]
We need to create a button at the top of the home screen in order to have the user be able to add their own tasks instead of having a preset of tasks @alexander2475 @mikey3410

**Comment by alexander2475** [comment]
@GiovaniFuentes Do we have a general mockup of what we're wanting the layout to look like? That way we have something to go off of and can be a little more coordinated.

**Comment by GiovaniFuentes** [comment]
So I remember how your layout looked last time we were in lab so I'm wondering if maybe the first 2 buttons / items in the grid layout could be a button which has + which allows for adding another task and the second column would have the xp bar that Chad is working on. What do you think do you have any other ideas? @alexander2475
