### ISSUE TITLE
Auto resize character page

### ISSUE THREAD

**Issue by GiovaniFuentes** [nmsu-cs/project-macintosh-mavericks-1#15]
@alexander2475 I was wondering if maybe you can help me figure out how to auto resize the character page like how you are doing it for the main home page, would very much appreciate it!

**Comment by alexander2475** [comment]
@GiovaniFuentes I can help more thoroughly in person or over call, but the rough jist of its is using the grid layout as it automatically resizes. 

example code:
```
setLayout(new GridLayout(2, 2, 20, 20));
```

There are some drawbacks with using this as our layout, but it should cover everything pretty well for the most part.

**Comment by GiovaniFuentes** [comment]
where do you set the layout and do you know what the numbers stand for? this is an example of some basic code I have on the character page
 JFrame window = new JFrame();
        window.setSize(800,600);
        window.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        window.getContentPane().setBackground(Color.black);
        window.setLayout(null);

        //new panel where labels will be located
        JPanel counterPanel = new JPanel();
        counterPanel.setBounds(100,100,200,100);
        counterPanel.setBackground(Color.black);
        counterPanel.setLayout(new GridLayout(2,1));
        window.add(counterPanel);
        
        I think i might be having the issue when adding the ".setBounds(x,y,width,height)"
        I will have to test if just doing a new grid layout without bounds how it will affect the UI. doing a grid layout like new GridLayout(2,1)) i know its two rows and two columns but what is the (2,2,20,20) the two 20's? @alexander2475
