### ISSUE TITLE
Incomplete

### ISSUE THREAD

**Issue by GiovaniFuentes** [nmsu-cs/project-macintosh-mavericks-1#3]
Will we be removing the "incomplete" button or will it be used to lose xp? or get some sort of maybe punishment?

**Comment by pattyl11** [comment]
@GiovaniFuentes You can @ members of your team to make sure they see your question. @mikey3410 @alexander2475 @ChadPine1991.

**Comment by alexander2475** [comment]
@GiovaniFuentes i like the idea of having an incomplete button that decreases XP if someone over planned as it promotes better and more realistic planning.

**Comment by mikey3410** [comment]
We can use it as punishment that would be cool to make them do the tasks
